WITH LASTPAIDCLICK AS (
    SELECT
        S.VISITOR_ID,
        S.VISIT_DATE,
        L.CREATED_AT,
        L.LEAD_ID,
        L.STATUS_ID,
        L.AMOUNT,
        S.SOURCE AS UTM_SOURCE,
        S.MEDIUM AS UTM_MEDIUM,
        S.CAMPAIGN AS UTM_CAMPAIGN,
        to_char(S.VISIT_DATE, 'YYYY-MM-DD') AS VISIT_DATES,
        row_number()
            OVER (PARTITION BY S.VISITOR_ID ORDER BY S.VISIT_DATE DESC)
            AS RW
    FROM SESSIONS AS S
    FULL JOIN LEADS AS L ON S.VISITOR_ID = L.VISITOR_ID
    WHERE S.MEDIUM != 'organic'
)
select
    sub.visitor_id,
WITH LASTPAIDCLICK AS (
    SELECT
        S.VISITOR_ID,
        S.VISIT_DATE,
        L.CREATED_AT,
        L.LEAD_ID,
        L.STATUS_ID,
        L.AMOUNT,
        S.SOURCE AS UTM_SOURCE,
        S.MEDIUM AS UTM_MEDIUM,
        S.CAMPAIGN AS UTM_CAMPAIGN,
        to_char(S.VISIT_DATE, 'YYYY-MM-DD') AS VISIT_DATES,
        to_char(L.CREATED_AT, 'YYYY-MM-DD') AS CREATED,
        row_number()
            OVER (PARTITION BY S.VISITOR_ID ORDER BY S.VISIT_DATE DESC)
            AS RN
    FROM SESSIONS AS S
    FULL JOIN LEADS AS L ON S.VISITOR_ID = L.VISITOR_ID
    WHERE S.MEDIUM != 'organic'
),
ADS AS (
    -- Первый запрос как подзапрос: объединение затрат из ya_ads и vk_ads
    SELECT
        to_char(CAMPAIGN_DATE, 'YYYY-MM-DD') AS DATE,
        UTM_SOURCE,
        UTM_MEDIUM,
        UTM_CAMPAIGN,
        sum(DAILY_SPENT) AS TOTAL
    FROM YA_ADS
    GROUP BY CAMPAIGN_DATE, UTM_SOURCE, UTM_MEDIUM, UTM_CAMPAIGN
    UNION
    SELECT
        to_char(CAMPAIGN_DATE, 'YYYY-MM-DD') AS DATE,
        UTM_SOURCE,
        UTM_MEDIUM,
        UTM_CAMPAIGN,
        sum(DAILY_SPENT) AS TOTAL
    FROM VK_ADS
    GROUP BY CAMPAIGN_DATE, UTM_SOURCE, UTM_MEDIUM, UTM_CAMPAIGN
)
SELECT
    LPC.VISIT_DATES AS VISIT_DATE,
    LPC.UTM_SOURCE,
    LPC.UTM_MEDIUM,
    LPC.UTM_CAMPAIGN,
    count(DISTINCT LPC.VISITOR_ID) AS VISITORS_COUNT,
    coalesce(ADS.TOTAL, 0) AS TOTAL_COST,
    count(LPC.LEAD_ID) FILTER (WHERE LPC.CREATED_AT > LPC.VISIT_DATE)
        AS LEADS_COUNT,
    count(LPC.LEAD_ID) FILTER (
        WHERE LPC.STATUS_ID = 142 AND LPC.CREATED_AT > LPC.VISIT_DATE
    ) AS PURCHASES_COUNT,
    coalesce(sum(LPC.AMOUNT), 0) AS REVENUE
FROM LASTPAIDCLICK AS LPC
LEFT JOIN ADS
    ON
        LPC.VISIT_DATES = ADS.DATE
        AND LPC.UTM_SOURCE = ADS.UTM_SOURCE
        AND LPC.UTM_MEDIUM = ADS.UTM_MEDIUM
        AND LPC.UTM_CAMPAIGN = ADS.UTM_CAMPAIGN
WHERE LPC.RN = 1
GROUP BY
    LPC.VISIT_DATES,
    LPC.UTM_SOURCE,
    LPC.UTM_MEDIUM,
    LPC.UTM_CAMPAIGN,
    ADS.TOTAL
ORDER BY
    REVENUE DESC NULLS LAST,
    VISIT_DATE ASC,
    VISITORS_COUNT DESC,
    UTM_SOURCE ASC, UTM_MEDIUM ASC, UTM_CAMPAIGN ASC