WITH LASTPAIDCLICK AS (
    SELECT
        S.VISITOR_ID,
        S.VISIT_DATE,
        L.CREATED_AT,
        L.LEAD_ID,
        L.STATUS_ID,
        L.AMOUNT,
        S.SOURCE AS UTM_SOURCE,
        S.MEDIUM AS UTM_MEDIUM,
        S.CAMPAIGN AS UTM_CAMPAIGN,
        to_char(S.VISIT_DATE, 'YYYY-MM-DD') AS VISIT_DATES,
        row_number()
            OVER (PARTITION BY S.VISITOR_ID ORDER BY S.VISIT_DATE DESC)
            AS RW
    FROM SESSIONS AS S
    FULL JOIN LEADS AS L ON S.VISITOR_ID = L.VISITOR_ID
    WHERE S.MEDIUM != 'organic'
)
SELECT
    SUB.VISITOR_ID,
    SUB.VISIT_DATE,
    SUB.UTM_SOURCE,
    SUB.UTM_MEDIUM,
    SUB.UTM_CAMPAIGN,
    SUB.LEAD_ID,
    SUB.CREATED_AT,
    SUB.AMOUNT,
    CLOSING_REASON,
    SUB.STATUS_ID
FROM SESSIONS AS S
LEFT JOIN LEADS AS L
    ON S.VISITOR_ID = L.VISITOR_ID
LEFT JOIN LASTPAIDCLICK AS SUB
    ON S.VISITOR_ID = SUB.VISITOR_ID
WHERE S.MEDIUM != 'organic' AND RW = 1
GROUP BY
    SUB.VISITOR_ID,
    SUB.VISIT_DATE,
    SUB.UTM_SOURCE,
    SUB.UTM_MEDIUM,
    SUB.UTM_CAMPAIGN,
    SUB.LEAD_ID,
    SUB.AMOUNT,
    SUB.CREATED_AT,
    CLOSING_REASON,
    SUB.STATUS_ID
ORDER BY
    AMOUNT DESC NULLS LAST,
    SUB.VISIT_DATE ASC,
    UTM_SOURCE ASC,
    UTM_MEDIUM ASC,
    UTM_CAMPAIGN ASC
